### ISSUE TITLE
LinkedIn Learner:  Build failed.

### ISSUE THREAD

**Issue by lacnunga** [wolftype/opengl_basics#1]
Hello

I have tried using the files in this repo while following Setting up OpenGL and CMake in OS X of Learning OpenGL. However, loading UaR_OpenGL.xcodeproj shows a complete different set of folders and files in Xcode and no 'Sources' folder. Anyway, I tried running .c files such as clipboard.c with no luck – Xcode returns Build failed.

As a matter of course, I made sure CMake and Xcode had been correctly installed on my instance of macOS Big Sur. I'm looking forward to hearing from you soon.

**Comment by wolftype** [comment]
Hi — cmake does generate a bunch of random files in Xcode generator (such
as clipboard).  Instead of running clipboard, what happens when you select
a different target from the lessons?  For example, “cube”?

Please also let me know what version of Xcode you are using.

**Comment by lacnunga** [comment]
Loading UaR_OpenGL.xcodeproj doesn't show me any files in the Project Navigator outside the xcode folder and loading the examples folder results in the cannot open error, so I can't even select any .cpp files outside the xcode folder as far as exercise files are concerned.

Just in case, I verified that I could run any swift source files in Xcode templates.

**Comment by wolftype** [comment]
I currently only have access to Mac os Catalina, so cannot duplicate.  If you can, I've made a few updates -- I suggest pulling this repo again with ```git pull``` and then seeing if you are able to run the examples directly from your terminal command line with: ```./run.sh examples/Cube.cpp```

Just to be clear, what version of xcode are you running?  Perhaps you could share a screen shot of the xcode window?  The the drop down on the top left of xcode is where you would select different targets to be built.   
<img width="424" alt="Screen Shot 2021-07-27 at 6 46 43 PM" src="https://user-images.githubusercontent.com/1120351/127250608-9b2ac12e-6b96-4437-aefa-2734d2afef64.png">

**Comment by lacnunga** [comment]
I'm using the latest version of Xcode, 12.5.1.  and the terminal command as stated above successfully ran.

When I tried to clone the repo using Xcode, the cloning process got stuck. Also, when I tried to pull the repo using Sourcetree, the repo could be cloned, but Xcode returned an error, so it must be to do with the repo having an issue with Big Sur:

https://ibb.co/HgCHQpR
https://ibb.co/5x8jMtH

**Comment by wolftype** [comment]
I wouldn’t suggest using Xcode to clone the repo.  Sourcetree is fine.  Can
you share a screen grab of what the cmake-generated Xcode project looks
like when you open it?

**Comment by lacnunga** [comment]
As I wrote above, the repo cloned using Sourcetree can't be opened in Xcode. There's really no more time for me to try troubleshooting the set-up problem, so I have to close this correspondence.
